"""add document relations for A0-03

Revision ID: 2d4921e32045
Revises: 7b982b8d9d4d
Create Date: 2026-08-18 19:29:22.818823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4921e32045'
down_revision: Union[str, Sequence[str], None] = '7b982b8d9d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('target_document_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'target_document_id', 'relation_type', name='uq_document_relations_source_target_type')
    )
    op.create_index(op.f('ix_document_relations_source_document_id'), 'document_relations', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_relations_target_document_id'), 'document_relations', ['target_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_relations_target_document_id'), table_name='document_relations')
    op.drop_index(op.f('ix_document_relations_source_document_id'), table_name='document_relations')
    op.drop_table('document_relations')
    # ### end Alembic commands ###
