"""add document application scopes

Revision ID: 3f821b397634
Revises: 9349d525f414
Create Date: 2026-08-20 13:34:59.023161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f821b397634'
down_revision: Union[str, Sequence[str], None] = '9349d525f414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_application_scopes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('related_document_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('scope_detail', sa.Text(), nullable=True),
    sa.Column('reference_nature', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_application_scopes_related_document_id'), 'document_application_scopes', ['related_document_id'], unique=False)
    op.create_index(op.f('ix_document_application_scopes_source_document_id'), 'document_application_scopes', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_application_scopes_source_version_id'), 'document_application_scopes', ['source_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_application_scopes_source_version_id'), table_name='document_application_scopes')
    op.drop_index(op.f('ix_document_application_scopes_source_document_id'), table_name='document_application_scopes')
    op.drop_index(op.f('ix_document_application_scopes_related_document_id'), table_name='document_application_scopes')
    op.drop_table('document_application_scopes')
    # ### end Alembic commands ###
