"""add document effectiveness alerts

Revision ID: 9349d525f414
Revises: 2d4921e32045
Create Date: 2026-08-19 19:04:06.429921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9349d525f414'
down_revision: Union[str, Sequence[str], None] = '2d4921e32045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_effectiveness_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('new_document_number', sa.String(length=100), nullable=False),
    sa.Column('new_document_title', sa.String(length=500), nullable=False),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('affected_document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affected_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_effectiveness_alerts_affected_document_id'), 'document_effectiveness_alerts', ['affected_document_id'], unique=False)
    op.drop_index(op.f('uq_documents_document_number_ci'), table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_documents_document_number_ci'), 'documents', [sa.literal_column('lower(document_number::text)')], unique=True)
    op.drop_index(op.f('ix_document_effectiveness_alerts_affected_document_id'), table_name='document_effectiveness_alerts')
    op.drop_table('document_effectiveness_alerts')
    # ### end Alembic commands ###
