"""add documents for A0-01

Revision ID: e5f874c488f7
Revises: 55ca200dd43a
Create Date: 2026-08-18 11:00:49.800784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f874c488f7'
down_revision: Union[str, Sequence[str], None] = '55ca200dd43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('legal_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        "uq_documents_document_number_ci",
        "documents",
        [
            sa.literal_column(
                "lower(document_number::text)"
            )
        ],
        unique=True,
    )
    op.create_index('ix_documents_issued_date', 'documents', ['issued_date'], unique=False)
    op.create_index('ix_documents_legal_status', 'documents', ['legal_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        "uq_documents_document_number_ci",
        table_name="documents",
    )

    op.drop_index(
        "ix_documents_legal_status",
        table_name="documents",
    )

    op.drop_index(
        "ix_documents_issued_date",
        table_name="documents",
    )

    op.drop_table(
        "documents"
    )
