from sqlalchemy import (
    Column,
    DateTime,
    Index,
    String,
    Table,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import UUID

from src.persistence.tenant.database import metadata


audit_logs = Table(
    "audit_logs",
    metadata,
    Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
    ),
    Column(
        "school_id",
        UUID(as_uuid=True),
        nullable=True,
    ),
    Column(
        "actor_id",
        UUID(as_uuid=True),
        nullable=True,
    ),
    Column(
        "actor_type",
        String(50),
        nullable=False,
    ),
    Column(
        "action",
        String(100),
        nullable=False,
    ),
    Column(
        "entity",
        String(100),
        nullable=False,
    ),
    Column(
        "entity_id",
        UUID(as_uuid=True),
        nullable=True,
    ),
    Column(
        "old_values",
        Text,
        nullable=True,
    ),
    Column(
        "new_values",
        Text,
        nullable=True,
    ),
    Column(
        "metadata",
        Text,
        nullable=True,
    ),
    Column(
        "ip_address",
        String(50),
        nullable=True,
    ),
    Column(
        "device_id",
        String(100),
        nullable=True,
    ),
    Column(
        "user_agent",
        String(500),
        nullable=True,
    ),
    Column(
        "trace_id",
        String(100),
        nullable=True,
    ),
    Column(
        "created_at",
        DateTime(timezone=True),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    ),
    Index(
        "ix_audit_logs_school_id",
        "school_id",
    ),
    Index(
        "ix_audit_logs_actor_id",
        "actor_id",
    ),
    Index(
        "ix_audit_logs_entity_entity_id",
        "entity",
        "entity_id",
    ),
    Index(
        "ix_audit_logs_created_at",
        "created_at",
    ),
    Index(
        "ix_audit_logs_trace_id",
        "trace_id",
    ),
)